title = "create-webapps"

[general]
first_launch = true
generate_desktop_file = true
systemwide_desktop_entry = false
webapps_directory = '/home/bella/WebApps'
locale = "en"

[advanced]
specialos = "none"
