title = 'create-webapps'

[advanced]
specialos = 'none'

[general]
first_launch = false
generate_desktop_file = true
locale = 'en'
systemwide_desktop_entry = false
webapps_directory = '/home/bella/WebApps'
